(function () {
  'use strict';
  var copy = {
    ru: {
      titleText: 'Приватность - Константин Васильев', description: 'Как портфолио использует localStorage, GitHub Pages, QA API Lab и FormSubmit для обратной связи.', skip: 'К содержанию', backLabel: 'Вернуться на главную', languageLabel: 'Выбор языка', eyebrow: 'ПРИВАТНОСТЬ / ПОНЯТНЫМ ЯЗЫКОМ', title: 'Не собираю<br /><i>лишнее.</i>', updated: 'Обновлено: 5 сентября 2026', intro: 'Это личный сайт-портфолио Константина Васильева. Здесь нет регистрации, рекламы и подключённой веб-аналитики. Добровольная форма обратной связи отправляет данные только после вашего согласия.', sectionsLabel: 'Разделы уведомления', storageTitle: 'Что хранится в браузере', storageText: 'Код сайта использует localStorage только для выбранного языка и отметки о закрытии информационного уведомления. Эти значения остаются на вашем устройстве и не отправляются владельцу сайта.', cookiesTitle: 'Cookies и трекеры', cookiesText: 'Код портфолио не устанавливает рекламные или аналитические cookies и не подключает пиксели слежения. При переходе к отправке формы FormSubmit и CAPTCHA могут обрабатывать технические данные по собственным правилам.', hostingTitle: 'Технические данные хостинга', hostingText: 'Сайт размещён на GitHub Pages. По документации GitHub, IP-адреса посетителей регистрируются и хранятся GitHub в целях безопасности независимо от наличия аккаунта.', githubDocs: 'Документация GitHub ↗', labTitle: 'Проверка API Lab', labText: 'При открытии страницы API Lab браузер автоматически отправляет GET-запрос к qa-api-lab.onrender.com, чтобы разбудить демо и показать его статус. Render и хостинг приложения могут получить IP-адрес и технические данные запроса. Ответ используется на странице только для индикатора готовности.', renderPrivacy: 'Политика Render ↗', linksTitle: 'Внешние ссылки', linksText: 'Telegram, RuStore, Google Drive, Mail.ru и другие внешние сервисы открываются только после нажатия на ссылку. На их страницах действуют собственные правила приватности.', formTitle: 'Форма обратной связи', formText: 'При отправке формы имя, email, сообщение и выбранный файл передаются сервису FormSubmit, а затем в почтовый ящик владельца сайта. Цель обработки - получить обращение и ответить на него. Отправка добровольна и доступна только после отметки согласия.', formDocs: 'Документация FormSubmit ↗', formPrivacy: 'Политика FormSubmit ↗', retentionTitle: 'Хранение и удаление', retentionText: 'По документации FormSubmit текст отправления хранится до 30 дней, а загруженные файлы недоступны в архиве API. Доставленная копия может оставаться в почтовом ящике до ручного удаления. Чтобы запросить удаление обращения, напишите на email ниже.', changeTitle: 'Если обработка изменится', changeText: 'При добавлении аналитики, рекламы или новых способов обработки данных это уведомление и механизм согласия будут пересмотрены до публикации изменений.', question: 'Вопрос по приватности или просьба удалить обращение?', back: 'На главную ↑', topLabel: 'Наверх'
    },
    en: {
      titleText: 'Privacy - Konstantin Vasiliev', description: 'How the portfolio uses localStorage, GitHub Pages, QA API Lab and FormSubmit for feedback.', skip: 'Skip to content', backLabel: 'Return to the homepage', languageLabel: 'Language selection', eyebrow: 'PRIVACY / IN PLAIN LANGUAGE', title: 'Nothing<br /><i>unnecessary.</i>', updated: 'Updated: September 5, 2026', intro: 'This is Konstantin Vasiliev’s personal portfolio. It has no registration, advertising or connected web analytics. The optional feedback form sends data only after your consent.', sectionsLabel: 'Notice sections', storageTitle: 'What is stored in your browser', storageText: 'The site code uses localStorage only for your language choice and acknowledgement of the information notice. These values stay on your device and are not sent to the site owner.', cookiesTitle: 'Cookies and trackers', cookiesText: 'The portfolio code sets no advertising or analytics cookies and loads no tracking pixels. If you continue to form submission, FormSubmit and CAPTCHA may process technical data under their own rules.', hostingTitle: 'Technical hosting data', hostingText: 'The site is hosted on GitHub Pages. According to GitHub documentation, GitHub logs and stores visitor IP addresses for security purposes, whether or not the visitor is signed in.', githubDocs: 'GitHub documentation ↗', labTitle: 'QA API Lab status check', labText: 'When you open the API Lab page, the browser automatically sends a GET request to qa-api-lab.onrender.com to wake the demo and display its status. Render and the app hosting service may receive the IP address and technical request data. The page uses the response only for its readiness indicator.', renderPrivacy: 'Render privacy policy ↗', linksTitle: 'External links', linksText: 'Telegram, RuStore, Google Drive, Mail.ru and other external services open only after you click a link. Their own privacy rules apply on their pages.', formTitle: 'Feedback form', formText: 'When you submit the form, your name, email, message and selected file are transferred to FormSubmit and then to the site owner’s email inbox. The purpose is to receive your message and reply. Submission is optional and available only after you mark your consent.', formDocs: 'FormSubmit documentation ↗', formPrivacy: 'FormSubmit privacy policy ↗', retentionTitle: 'Retention and deletion', retentionText: 'FormSubmit states that textual submissions are retained for up to 30 days and uploaded files are unavailable in its API archive. The delivered copy may remain in the mailbox until it is manually deleted. Use the email below to request deletion of your message.', changeTitle: 'If processing changes', changeText: 'If analytics, advertising or new processing methods are added, this notice and the consent mechanism will be reviewed before publication.', question: 'A privacy question or a request to delete your message?', back: 'Homepage ↑', topLabel: 'Back to top'
    }
  };
  var buttons = document.querySelectorAll('[data-language]');
  var topButton = document.querySelector('[data-back-to-top]');
  var metaDescription = document.querySelector('meta[name="description"]');
  function storedLanguage() { try { return window.localStorage.getItem('kv-site-language'); } catch (error) { return null; } }
  function setLanguage(language, persist) {
    var selected = copy[language] ? language : 'ru';
    var text = copy[selected];
    document.documentElement.lang = selected;
    document.title = text.titleText;
    if (metaDescription) metaDescription.setAttribute('content', text.description);
    document.querySelectorAll('[data-privacy-i18n]').forEach(function (node) { var key = node.getAttribute('data-privacy-i18n'); if (text[key]) node.textContent = text[key]; });
    document.querySelectorAll('[data-privacy-html]').forEach(function (node) { var key = node.getAttribute('data-privacy-html'); if (text[key]) node.innerHTML = text[key]; });
    document.querySelectorAll('[data-privacy-aria]').forEach(function (node) { var key = node.getAttribute('data-privacy-aria'); if (text[key]) node.setAttribute('aria-label', text[key]); });
    buttons.forEach(function (button) { var active = button.getAttribute('data-language') === selected; button.classList.toggle('is-active', active); button.setAttribute('aria-pressed', String(active)); });
    document.querySelectorAll('[data-home-link]').forEach(function (link) { link.setAttribute('href', '../?lang=' + selected); });
    if (persist) { try { window.localStorage.setItem('kv-site-language', selected); } catch (error) { return; } var url = new URL(window.location.href); url.searchParams.set('lang', selected); window.history.replaceState({}, '', url.pathname + url.search); }
  }
  buttons.forEach(function (button) { button.addEventListener('click', function () { setLanguage(button.getAttribute('data-language'), true); }); });
  setLanguage(new URLSearchParams(window.location.search).get('lang') || storedLanguage() || 'ru', false);
  function updateTop() { topButton.classList.toggle('is-visible', window.scrollY > 500); }
  window.addEventListener('scroll', updateTop, { passive: true }); updateTop();
  topButton.addEventListener('click', function () { window.scrollTo({ top: 0, behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); });
}());
