(function () {
  'use strict';
  var copy = {
    ru: {
      titleText: 'Приватность - Константин Васильев', skip: 'К содержанию', backLabel: 'Вернуться на главную', languageLabel: 'Выбор языка', eyebrow: 'ПРИВАТНОСТЬ / ПОНЯТНЫМ ЯЗЫКОМ', title: 'Не собираю<br /><i>лишнее.</i>', updated: 'Обновлено: 4 сентября 2026', intro: 'Это личный сайт-портфолио Константина Васильева. Здесь нет регистрации, формы обратной связи, рекламы и подключённой веб-аналитики.', sectionsLabel: 'Разделы уведомления', storageTitle: 'Что хранится в браузере', storageText: 'Код сайта использует localStorage только для выбранного языка и отметки о закрытии информационного уведомления. Эти значения остаются на вашем устройстве и не отправляются владельцу сайта.', cookiesTitle: 'Cookies и трекеры', cookiesText: 'Код сайта не устанавливает рекламные или аналитические cookies и не подключает пиксели слежения. Поэтому кнопки «принять» и «отклонить» необязательные cookies здесь нет.', hostingTitle: 'Технические данные хостинга', hostingText: 'Сайт размещён на GitHub Pages. По документации GitHub, IP-адреса посетителей регистрируются и хранятся GitHub в целях безопасности независимо от наличия аккаунта.', githubDocs: 'Документация GitHub ↗', labTitle: 'Проверка API Lab', labText: 'При открытии страницы API Lab браузер автоматически отправляет GET-запрос к qa-api-lab.onrender.com, чтобы разбудить демо и показать его статус. Render и хостинг приложения могут получить IP-адрес и технические данные запроса. Ответ используется на странице только для индикатора готовности.', renderPrivacy: 'Политика Render ↗', linksTitle: 'Внешние ссылки', linksText: 'Telegram, RuStore, Google Drive, Mail.ru и другие внешние сервисы открываются только после нажатия на ссылку. На их страницах действуют собственные правила приватности.', contactTitle: 'Связь и данные', contactText: 'Если вы напишете по email или в Telegram, данные сообщения обрабатываются в выбранном вами сервисе и только для ответа на обращение. Сам сайт содержимое переписки не получает и не хранит.', changeTitle: 'Если сайт изменится', changeText: 'При добавлении формы, аналитики, рекламы или новых способов обработки данных это уведомление и механизм согласия нужно пересмотреть до публикации изменений.', question: 'Вопрос по приватности или просьба удалить переписку?', back: 'На главную ↑', topLabel: 'Наверх'
    },
    en: {
      titleText: 'Privacy - Konstantin Vasiliev', skip: 'Skip to content', backLabel: 'Return to the homepage', languageLabel: 'Language selection', eyebrow: 'PRIVACY / IN PLAIN LANGUAGE', title: 'Nothing<br /><i>unnecessary.</i>', updated: 'Updated: September 4, 2026', intro: 'This is Konstantin Vasiliev’s personal portfolio. It has no registration, contact form, advertising or connected web analytics.', sectionsLabel: 'Notice sections', storageTitle: 'What is stored in your browser', storageText: 'The site code uses localStorage only for your language choice and acknowledgement of the information notice. These values stay on your device and are not sent to the site owner.', cookiesTitle: 'Cookies and trackers', cookiesText: 'The site code sets no advertising or analytics cookies and loads no tracking pixels. There is therefore no unnecessary accept or reject control for optional cookies.', hostingTitle: 'Technical hosting data', hostingText: 'The site is hosted on GitHub Pages. According to GitHub documentation, GitHub logs and stores visitor IP addresses for security purposes, whether or not the visitor is signed in.', githubDocs: 'GitHub documentation ↗', labTitle: 'QA API Lab status check', labText: 'When you open the API Lab page, the browser automatically sends a GET request to qa-api-lab.onrender.com to wake the demo and display its status. Render and the app hosting service may receive the IP address and technical request data. The page uses the response only for its readiness indicator.', renderPrivacy: 'Render privacy policy ↗', linksTitle: 'External links', linksText: 'Telegram, RuStore, Google Drive, Mail.ru and other external services open only after you click a link. Their own privacy rules apply on their pages.', contactTitle: 'Messages and data', contactText: 'If you contact me by email or Telegram, your message is processed in the service you chose and only to reply. This website does not receive or store the conversation.', changeTitle: 'If the site changes', changeText: 'If a form, analytics, advertising or another data-processing method is added, this notice and the consent mechanism must be reviewed before those changes are published.', question: 'A privacy question or a request to delete a conversation?', back: 'Homepage ↑', topLabel: 'Back to top'
    }
  };
  var buttons = document.querySelectorAll('[data-language]');
  var topButton = document.querySelector('[data-back-to-top]');
  function storedLanguage() { try { return window.localStorage.getItem('kv-site-language'); } catch (error) { return null; } }
  function setLanguage(language, persist) {
    var selected = copy[language] ? language : 'ru';
    var text = copy[selected];
    document.documentElement.lang = selected;
    document.title = text.titleText;
    document.querySelectorAll('[data-privacy-i18n]').forEach(function (node) { var key = node.getAttribute('data-privacy-i18n'); if (text[key]) node.textContent = text[key]; });
    document.querySelectorAll('[data-privacy-html]').forEach(function (node) { var key = node.getAttribute('data-privacy-html'); if (text[key]) node.innerHTML = text[key]; });
    document.querySelectorAll('[data-privacy-aria]').forEach(function (node) { var key = node.getAttribute('data-privacy-aria'); if (text[key]) node.setAttribute('aria-label', text[key]); });
    buttons.forEach(function (button) { var active = button.getAttribute('data-language') === selected; button.classList.toggle('is-active', active); button.setAttribute('aria-pressed', String(active)); });
    document.querySelectorAll('[data-home-link]').forEach(function (link) { link.setAttribute('href', '../?lang=' + selected); });
    if (persist) { try { window.localStorage.setItem('kv-site-language', selected); } catch (error) { return; } var url = new URL(window.location.href); url.searchParams.set('lang', selected); window.history.replaceState({}, '', url.pathname + url.search); }
  }
  buttons.forEach(function (button) { button.addEventListener('click', function () { setLanguage(button.getAttribute('data-language'), true); }); });
  setLanguage(new URLSearchParams(window.location.search).get('lang') || storedLanguage() || 'ru', false);
  function updateTop() { topButton.classList.toggle('is-visible', window.scrollY > 500); }
  window.addEventListener('scroll', updateTop, { passive: true }); updateTop();
  topButton.addEventListener('click', function () { window.scrollTo({ top: 0, behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); });
}());
